on:
  push:
    branches:
      - main

jobs:
  build_site:
    runs-on: ubuntu-latest
    name: Builds site to directory
    steps:
      - uses: actions/checkout@v2
      - name: Build
        uses: bm424/bm424.github.io@v1
      - run: mkdir build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
